# Generated by Django 5.2.8 on 2025-12-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Başlık')),
                ('file', models.FileField(blank=True, null=True, upload_to='materials/pdfs/', verbose_name='Dosya')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='Video URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('material_type', models.CharField(choices=[('pdf', 'PDF Document'), ('video', 'Video File')], default='pdf', max_length=10, verbose_name='Materyal Türü')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='Ders')),
            ],
        ),
    ]
