# Generated by Django 5.2.7 on 2025-12-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
    ]
