# Generated by Django 5.2.8 on 2025-12-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Ders Adı')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='URL Yolu (Slug)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='courses/', verbose_name='Ders Resmi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
