# Generated by Django 5.2.8 on 2025-12-22 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Yazılım', 'Yazılım'), ('Akademik', 'Akademik'), ('Backend', 'Backend')], default='Yazılım', max_length=50, verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default='Eğitmen Bilgisi Yok', max_length=100, verbose_name='Eğitmen Adı'),
        ),
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktif mi? (Yakında değilse aktif)'),
        ),
        migrations.AddField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=5.0, max_digits=2, verbose_name='Puan'),
        ),
    ]
