# Generated by Django 5.2.7 on 2025-12-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_category_course_instructor_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('Yazılım Mühendisliği', 'Yazılım Mühendisliği'), ('Bilgisayar Programlama', 'Bilgisayar Programlama'), ('Akademik', 'Akademik'), ('Matematik', 'Matematik'), ('Fizik', 'Fizik'), ('Kimya', 'Kimya'), ('Tasarım', 'Tasarım'), ('Kişisel Gelişim', 'Kişisel Gelişim'), ('Pazarlama', 'Pazarlama'), ('Fotoğrafçılık', 'Fotoğrafçılık'), ('Müzik', 'Müzik')], default='Yazılım', max_length=50, verbose_name='Kategori'),
        ),
    ]
