"""
Django settings for gelisimKapsul project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


load_dotenv() # .env dosyasını yükler

# PAYTR AYARLARI (Artık güvenli!)
# .env okuyamadığı için geçici olarak elle yazıyoruz
#PAYTR_MERCHANT_ID = '000000000' # güvenli olması için gerçek değeri saklandı
#PAYTR_MERCHANT_KEY = '0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p'
#PAYTR_MERCHANT_SALT = '0a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p'
#PAYTR_TEST_MODE = 1  # Test modunu etkinleştir (1: etkin, 0: devre dışı)

PAYTR_MERCHANT_ID='650955'
PAYTR_MERCHANT_KEY='M8uLqiuL4wJT5ZWX'
PAYTR_MERCHANT_SALT='orRSMWop8SD5wQb1'
PAYTR_TEST_MODE=1
#DEBUG=True

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=%cpqilbucbbbnvlyg(rov9i55q(im8zk(z0c)59j-616$icwh'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'gelisimKapsul',
    'accounts',
    'courses',
    'dashboard',
    'materials',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'gelisimKapsul.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'gelisimKapsul.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'tr-TR'

TIME_ZONE = 'Europe/Istanbul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTH_USER_MODEL = 'accounts.CustomUser'

# --- EMAIL AYARLARI (GMAIL) ---
# Django'nun mail göndermek için kullanacağı altyapı
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# GÖNDERİCİ BİLGİLERİ
# Buraya KENDİ kullandığın aktif bir gmail adresini yaz.
# Django bu adresi kullanarak mail atacak.
EMAIL_HOST_USER = 'aliceylan024@gmail.com' 

# BURASI ÇOK ÖNEMLİ:
# Buraya normal gmail şifreni YAZMA!
# Google'dan alacağın 16 haneli "Uygulama Şifresi"ni yazacaksın.
EMAIL_HOST_PASSWORD = 'vpnzuhjfykasidbv'
